# Generated by Django 2.2.3 on 2019-07-19 13:29

import articles.utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=131072)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('symbol_type', models.CharField(choices=[(articles.utils.enums.ReferenceSymbolType(1), 1), (articles.utils.enums.ReferenceSymbolType(2), 2)], max_length=32)),
            ],
        ),
    ]
