# Generated by Django 2.2.3 on 2019-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='references',
            field=models.ManyToManyField(to='articles.Reference'),
        ),
    ]
