# Generated by Django 2.2.3 on 2019-07-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190719_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='number',
        ),
    ]
